### ISSUE TITLE
Add worldCopyJump feature to Map object

### ISSUE THREAD

**Issue by golimarrrr** [mstahv/g-leaflet#24]
It's present in Leaflet (http://leafletjs.com/reference.html#map-worldcopyjump) but missing in g-leaflet.

**Comment by octavm** [comment]
To enable worldCopyJump feature, use LMap method:

setCustomInitOption("worldCopyJump", true) ;

**Comment by golimarrrr** [comment]
Isn't this for v-leaflet?

**Comment by octavm** [comment]
Yes, nothing is required in g-leaflet
