### ISSUE TITLE
Css in leaflet fails to compile when CssResource.enableGss flag is turned on

### ISSUE THREAD

**Issue by gxtUser** [mstahv/g-leaflet#25]
After turning on the Gss flag, the CSS to GSS conversion fails in leaflet.css with these errors (GWT v2.7):

                     [ERROR] Error in [auto-converted gss files from : [jar:file:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 56]: GSS constant not defined: M11
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 72]: GSS constant not defined: M12
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 88]: GSS constant not defined: M21
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 105]: GSS constant not defined: M22
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 52]: GSS constant not defined: M11
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/...2/g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 68]: GSS constant not defined: M12
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 84]: GSS constant not defined: M21
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 101]: GSS constant not defined: M22
         [ERROR] Errors in 'org/peimari/gleaflet/client/resources/LeafletResourceInjector.java'
            [ERROR] Line 11: Failed to resolve 'org.peimari.gleaflet.client.resources.LeafletClienBundle' via deferred binding

**Comment by gxtUser** [comment]
Thank you!

**Comment by tbroyer** [comment]
@mstahv You should also provide a `leaflet.gss` file so that users don't need to turn on on-the-fly conversion. Copy/paste your `leaflet.css` to https://css2gss.appspot.com/ and copy/paste the result into a `leaflet.gss` file. GWT will automatically pick the appropriate file depending on whether GSS is turned on or not.
