### ISSUE TITLE
literal() is not needed in -ms-filter and is actually broken

### ISSUE THREAD

**Issue by tbroyer** [mstahv/g-leaflet#27]
`literal()` is not needed for `-ms-filter` as the value is a simple CSS string.

Actually, it even generates broken CSS because GWT will remove the quotes inside the `literal()` value.
This can be seen at http://v3.tahvonen.fi/vleafletexample/ (open dev tools and search for `-ms-filter` – e.g. in Chrome, use the kebab menu at the top right of dev tools and select "search in all files", then search for `-ms-filter`)

**Comment by mstahv** [comment]
fixed in https://github.com/mstahv/g-leaflet/commit/5a590b4ad6f002bbfc53bb4e341040a2081d1682

Didn't test though how it works, need to try tomorrow at the office with our IE test cluster.

Thanks for the heads up!
