### ISSUE TITLE
Circle radius reported in feet instead of meters

### ISSUE THREAD

**Issue by dominic-simplan** [mstahv/g-leaflet#54]
Hi,
seems like the radius of a circle is always reported as feet, while the leaflet default should be meters (See http://leafletjs.com/reference-1.3.0.html#circle-getradius)?

Is there any way to change this to meters?

**Comment by mstahv** [comment]
For me it is meters. Could you provide an example where it is reported wrong? Maybe you background map is in wrong projection?

**Comment by dominic-simplan** [comment]
Hi,
thanks for your feedback!
I've now checked the v-leaflet-draw demo and it is working correctly. However I couldn't find much differences between the demo and my code, so I've upgraded v-leaflet from 2.0.2 to 2.0.4 and v-leaflet-draw from 2.0.0 to 2.0.1. Finally the circle radius is reported as km! Maybe there was an issue in the underlying leaflet library...
